apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: autopilot
  # This is an extra long description
  description: SaaS automated deployment
  links:
    - url: 
      title: GitHub Repo
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: liranc
